name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: zxzinn
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Taipei
          config_display: regular
          config_padding: 0, 8 + 11%
          repositories_affiliations: owner, collaborator, organization_member
          
          # Lines
          plugin_lines: yes
          plugin_lines_sections: history
          plugin_lines_repositories_limit: 0
          plugin_lines_history_limit: 1
          plugin_lines_delay: 30
          
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          plugin_languages_indepth: yes
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          
          # Notable
          plugin_notable: yes
          plugin_notable_filter: stars:>50
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          
          # Topics
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 15
          
          # Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
